framework:
    cache:
        app: cache.adapter.filesystem
        
        pools:
            # Cache pour les publications (5 minutes)
            app.cache.publications:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
                tags: true
                
            # Cache pour les commentaires (2 minutes)
            app.cache.comments:
                adapter: cache.adapter.filesystem
                default_lifetime: 120
                tags: true
                
            # Cache pour les utilisateurs (10 minutes)
            app.cache.users:
                adapter: cache.adapter.filesystem
                default_lifetime: 600
                tags: true