nelmio_api_doc:
    documentation:
        info:
            title: Instagrume API
            description: L'API de Instagrume
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   bearerAuth: []
        tags:
            -   name: Authentification
            -   name: Utilisateur
            -   name: Publication
            -   name: Commentaire
            -   name: Like
            -   name: Dislike
            -   name: Moderation
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
